# Generated by Django 4.2.8 on 2024-03-14 03:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("price", models.IntegerField()),
                ("area", models.DecimalField(decimal_places=1, max_digits=10)),
                ("description", models.TextField()),
                ("address", models.CharField(max_length=255)),
                ("hot_post", models.BooleanField(default=False)),
                (
                    "end_date",
                    models.DateTimeField(
                        default=datetime.datetime(2024, 4, 13, 10, 55, 14, 937064)
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNAPPROVED", "UNAPPROVED"),
                            ("FOR_RENT", "FOR_RENT"),
                            ("FULL", "FULL"),
                        ],
                        default="UNAPPROVED",
                        max_length=20,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("RENT", "RENT"), ("SALE", "SALE")], max_length=10
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
