# Generated by Django 4.2.7 on 2024-03-13 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hot_post",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="post",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 12, 9, 27, 38, 938418)
            ),
        ),
    ]
