# Generated by Django 4.2.8 on 2024-03-14 03:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 13, 10, 55, 26, 257864)
            ),
        ),
    ]
