# Generated by Django 4.2.8 on 2024-03-13 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_post_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="end_date",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 4, 12, 15, 42, 11, 975321)
            ),
        ),
    ]
