# Generated by Django 4.2.8 on 2024-03-14 08:55

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("favorites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favorite",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
