# Generated by Django 4.2.8 on 2024-03-14 03:55

from django.db import migrations, models
import django.db.models.deletion
import images.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0002_alter_post_end_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        storage=images.models.S3MediaStorage(), upload_to=""
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="posts.post"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
