# Generated by Django 4.2.8 on 2024-03-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="archived",
        ),
        migrations.RemoveField(
            model_name="image",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="image",
            name="modified_at",
        ),
        migrations.AlterField(
            model_name="image",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
